#1894 : Fix for path in PackageWithPyInstaller
